package com.enterprise.expense.enums;
public enum ClaimStatus {
    DRAFT, SUBMITTED, TEAM_LEAD_APPROVED, TEAM_LEAD_REJECTED,
    MANAGER_APPROVED, MANAGER_REJECTED, FINANCE_VERIFIED,
    FINANCE_REJECTED, PAYMENT_PROCESSED, ESCALATED, CANCELLED
}
